In [1]:
import pandas as pd

In [30]:
df = pd.read_csv("datasets/icu.csv")
df.head()

,Unnamed: 0.1,Unnamed: 0,AGE,SEX,ARREMS,TEMPF,PULSE,RESPR,BPSYS,BPDIAS,POPCT,CEBVD,EDDIAL,CHF,ALZHD,DIABETES,CAD,EDHIV,NOCHRON,ADMIT
0,52907,142119,38.0,0,0.0,98.4,93.0,16.0,128.0,74.0,98.0,0,0,0,0,0,0,0,1.0,0
1,46802,133953,52.0,0,0.0,97.0,60.0,16.0,122.0,72.0,97.0,0,0,0,0,0,0,0,0.0,0
2,46513,133637,62.0,1,0.0,98.2,98.0,18.0,226.0,108.0,98.0,1,0,0,0,1,0,0,0.0,0
3,87392,187618,74.0,1,0.0,97.8,78.0,18.0,183.0,94.0,100.0,0,0,0,0,0,0,0,0.0,0
4,100789,204947,30.0,1,1.0,98.1,136.0,18.0,133.0,73.0,99.0,0,0,0,0,0,0,0,1.0,0

In [29]:
df.columns[:30]

Index(['Unnamed: 0.1', 'Unnamed: 0', 'AGE', 'SEX', 'ARREMS', 'TEMPF', 'PULSE',
       'RESPR', 'BPSYS', 'BPDIAS', 'POPCT', 'CEBVD', 'EDDIAL', 'CHF', 'ALZHD',
       'DIABETES', 'CAD', 'EDHIV', 'NOCHRON', 'Double vision (diplopia)',
       'Legal problems', 'Stiffness, site unspecified', 'Flatulence',
       'Fracture/dislocation of hand and fingers',
       'Leg cramps, contractures, spasms', 'Minor surgery',
       'Small volume of urine', 'Swollen or enlarged glands',
       'Decreased heartbeat', 'Difficulty eating'],
      dtype='object')

In [28]:
list(df.iloc[1,:])

[46802,
 133953,
 52.0,
 0,
 0.0,
 97.0,
 60.0,
 16.0,
 122.0,
 72.0,
 97.0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0.0,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 True,
 False,
 False,
 False,
 False,
 True,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 False,
 0]

In [8]:
df["ADMIT"].value_counts()

ADMIT
Discharge             91702
Hospitalization        8479
Critical care unit     1643
Name: count, dtype: int64

In [5]:
df = df.drop("Unnamed: 0", axis=1)
df.head()
# df.to_csv("datasets/dataset.csv")

,AGE,SEX,ARREMS,TEMPF,PULSE,RESPR,BPSYS,BPDIAS,POPCT,CEBVD,CHF,EDHIV,NOCHRON,ADMIT,IMMEDR
0,36.0,Female,Yes,98.3,89.0,18.0,137.0,88.0,98.0,No,No,No,No,Not applicable,Urgent
1,26.0,Male,Yes,98.0,100.0,18.0,129.0,76.0,98.0,No,No,No,No,Not applicable,Urgent
2,82.0,Female,Yes,98.5,Blank,18.0,166.0,90.0,97.0,No,Yes,No,No,Critical care unit,Emergent
3,23.0,Female,No,98.7,76.0,18.0,138.0,77.0,98.0,No,No,No,Yes,Not applicable,Urgent
4,52.0,Female,Yes,98.7,83.0,21.0,139.0,80.0,99.0,No,No,No,No,Not applicable,Emergent